language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install: 
  - echo "Aquí se instalan las dependencias"
  - pip install django

before_script: 
  - echo "Antes de ejecutar un script"

script: 
  - cd PruebaDjango
  - python manage.py runserver

notifications:
email: false